In [1]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(a[0])

[1 2 3 4 5]
1


In [3]:
b = np.array([[1, 2, 3, 4], [5, 6, 6, 8], [9, 10, 11, 12]])
print(b)

[[ 1  2  3  4]
 [ 5  6  6  8]
 [ 9 10 11 12]]


In [8]:
c = np.empty(2)
print(c)
d = np.ones(2)
print(d)
e = np.zeros(2)
print(e)

[2.00000000e+000 6.95297528e-310]
[1. 1.]
[0. 0.]
